plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'com.scheduledreminders.alarmnative'
version = '0.1.0'

android {
  namespace "com.scheduledreminders.alarmnative"
  defaultConfig {
    versionCode 1
    versionName "0.1.0"
  }
  lintOptions {
    abortOnError false
  }
}
