/**
 * Domain types — the vocabulary the rest of the app shares.
 *
 * HOW TO READ THIS FILE
 * ---------------------
 * These interfaces are the *contract* between the UI, SQLite, and Android.
 * Change a field here, then follow the TypeScript errors into repositories
 * and screens. That is the point of TypeScript for this project.
 *
 * Three nested ideas (memorize these names):
 *
 *   AlarmTemplate  a time-of-day reminder that lives inside a routine
 *                  ("Wake up" at 06:00). It has NO calendar date.
 *
 *   Routine        a named group of templates ("Work day").
 *
 *   Schedule       when a routine applies on the calendar
 *                  (one date, or repeating Mon–Fri starting next week).
 *
 * The app then *materializes* AlarmOccurrence rows: concrete fire times
 * ("Wake up on 2026-09-21 at 06:00"). Those rows are what you hand to
 * Android AlarmManager. Native code should not know what a "routine" is.
 *
 * IDs: we use string UUIDs generated in JavaScript (see notImplemented helper
 * usage in the repos). SQLite is fine with TEXT primary keys. The one integer
 * you MUST keep is nativeRequestCode — Android PendingIntent request codes
 * are 32-bit ints, and collisions silently replace each other.
 */

/** Calendar day in the device's local timezone, `YYYY-MM-DD`. Never store a JS Date in SQLite. */
export type IsoDate = string;

/**
 * JS `Date.getDay()` numbers: 0 = Sunday … 6 = Saturday.
 * "Work day" Mon–Fri is `[1, 2, 3, 4, 5]`.
 */
export type Weekday = 0 | 1 | 2 | 3 | 4 | 5 | 6;

export type ScheduleKind = 'once' | 'weekly';

export type OccurrenceStatus = 'pending' | 'fired' | 'dismissed' | 'snoozed' | 'cancelled';

export type Routine = {
  id: string;
  name: string;
  /** Hex color for calendar dots, e.g. `#3B82F6`. */
  color: string;
  createdAtMs: number;
  updatedAtMs: number;
};

export type AlarmTemplate = {
  id: string;
  routineId: string;
  name: string;
  /** 0–23, local wall clock. */
  hour: number;
  /** 0–59, local wall clock. */
  minute: number;
  enabled: boolean;
  vibrate: boolean;
  /** Minutes to push the fire time when the user hits snooze. 0 = no snooze. */
  snoozeMinutes: number;
  /**
   * Optional content URI or bundled asset key for the sound.
   * Playing it is a native/Foreground Service problem, not a JS one.
   */
  soundKey: string | null;
};

export type Schedule = {
  id: string;
  routineId: string;
  kind: ScheduleKind;
  /**
   * Inclusive start. For `once`, this IS the date the routine runs.
   * For `weekly`, this is the first day the rule is allowed to apply
   * (not necessarily a matching weekday).
   */
  startDate: IsoDate;
  /** Inclusive end, or null = forever. */
  endDate: IsoDate | null;
  /**
   * Ignored when kind === 'once'.
   * Stored in SQLite as JSON text, e.g. `[1,2,3,4,5]`.
   */
  daysOfWeek: Weekday[];
  enabled: boolean;
};

/**
 * A hole (or extra day) punched into a repeating schedule.
 * `skip` = "no work-day alarms on this holiday".
 * `add`  = optional later feature ("run Work day on this Saturday").
 */
export type ScheduleException = {
  id: string;
  scheduleId: string;
  date: IsoDate;
  kind: 'skip' | 'add';
};

/**
 * One concrete alarm the OS should fire.
 * Generated by src/domain/occurrenceGenerator.ts, saved by occurrencesRepo,
 * registered with Android by src/services/alarmSync.ts.
 */
export type AlarmOccurrence = {
  id: string;
  alarmTemplateId: string;
  scheduleId: string;
  /** Unix epoch milliseconds, local wall time converted to UTC instant. */
  fireAtMs: number;
  /**
   * Integer passed to AlarmManager / PendingIntent.
   * Must be unique among all currently scheduled native alarms.
   * Suggestion: keep a counter in `settings`, or hash id → 32-bit int carefully.
   */
  nativeRequestCode: number;
  status: OccurrenceStatus;
};

export type AppSettings = {
  /** How many days ahead to generate occurrences. */
  horizonDays: number;
  defaultSnoozeMinutes: number;
  defaultSoundKey: string | null;
  /** Next unused Android request code. Increment when you assign one. */
  nextRequestCode: number;
};

/** Convenience shape for the calendar UI: "this date runs this routine". */
export type DayAssignment = {
  date: IsoDate;
  routine: Routine;
  schedule: Schedule;
};
